databases:
  - name: alphaquest-db
    plan: free
    databaseName: alphaquest
    user: alphaquest

services:
  - type: web
    plan: free
    name: alphaquest-backend
    runtime: python
    buildCommand: 'cd backend && ./build.sh'
    startCommand: 'cd backend && python -m gunicorn trading_signals.wsgi:application'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: alphaquest-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: CORS_ALLOWED_ORIGINS
        value: ""  # Add your frontend URL here when deployed
      - key: WEB_CONCURRENCY
        value: 4

  - type: web
    plan: free
    name: alphaquest-frontend
    runtime: node
    buildCommand: 'cd frontend && npm install && npm run build'
    startCommand: 'cd frontend && npx serve -s build -p $PORT'
    envVars:
      - key: NODE_ENV
        value: production
      - key: REACT_APP_API_URL
        value: https://alphaquest-backend.onrender.com