services:
  - type: web
    plan: free
    name: alphaquest-backend
    runtime: python
    pythonVersion: "3.11.9"
    buildCommand: 'cd backend && pip install --upgrade pip setuptools wheel && pip install --no-cache-dir --prefer-binary -r requirements-minimal.txt && pip install sympy scipy yfinance && python manage.py collectstatic --noinput && python manage.py migrate'
    startCommand: 'cd backend && gunicorn trading_signals.wsgi:application --bind 0.0.0.0:$PORT --workers 1 --timeout 300 --max-requests 50 --max-requests-jitter 10 --keep-alive 2 --log-level info'
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: CORS_ALLOWED_ORIGINS
        value: ""  # Add your frontend URL here when deployed
      - key: WEB_CONCURRENCY
        value: 1
      - key: PYTHONPATH
        value: "/opt/render/project/src/backend"

  - type: web
    plan: free
    name: alphaquest-frontend
    runtime: node
    buildCommand: 'cd frontend && npm install && npm run build'
    startCommand: 'cd frontend && npx serve -s build -p $PORT'
    envVars:
      - key: NODE_ENV
        value: production
      - key: REACT_APP_API_URL
        value: https://alphaquest-backend.onrender.com