services:
  - type: web
    plan: free
    name: alphaquest-backend
    runtime: python
    buildCommand: 'cd backend && ./build.sh'
    startCommand: 'cd backend && gunicorn trading_signals.wsgi:application --bind 0.0.0.0:$PORT --workers 1 --timeout 120 --max-requests 100 --preload'
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: CORS_ALLOWED_ORIGINS
        value: ""  # Add your frontend URL here when deployed
      - key: WEB_CONCURRENCY
        value: 1
      - key: PYTHONPATH
        value: "/opt/render/project/src/backend"

  - type: web
    plan: free
    name: alphaquest-frontend
    runtime: node
    buildCommand: 'cd frontend && npm install && npm run build'
    startCommand: 'cd frontend && npx serve -s build -p $PORT'
    envVars:
      - key: NODE_ENV
        value: production
      - key: REACT_APP_API_URL
        value: https://alphaquest-backend.onrender.com